sudo: false
language: node_js
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
after_success:
- cat coverage/lcov.info | ./node_modules/.bin/codecov
- cat coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter
- cat coverage/lcov.info | ./node_modules/.bin/coveralls
cache:
  directories:
  - bower_components
  - node_modules
